SonarSource/eslint-plugin-sonarjs

package.json

add eslint 6 to peerDeps

---

README.md
docs/rules/no-same-line-conditional.md
ruling/snapshots/no-same-line-conditional
src/index.ts
src/rules/no-same-line-conditional.ts
src/utils/locations.ts
tests/rules/no-same-line-conditional.test.ts

add rule no-same-line-conditional

---

README.md

To avoid the "error" displayed below in readme (since comments are not allowed in JSON), we could replace ` ```json ` with ` ```javascript ` in markdown. 
Also, `etc` has been replaced by `etc.` ([source](https://en.wikipedia.org/wiki/Et_cetera))

Fix highlighted JSON error in README markdown

---

README.md
docs/rules/no-inverted-boolean-check.md

docs: indicate rule that is fixable (consistent to how other fixable rules are documented with wrench)

Docs: Indicate rule 'no-inverted-boolean-check' is fixable

---

src/rules/no-inverted-boolean-check.ts
src/rules/prefer-while.ts

- Indicate rules that are fixable with `meta.fixable` property
Per the ESLint docs at https://eslint.org/docs/developer-guide/working-with-rules#rule-basics :
> Important: Without the fixable property, ESLint does not apply fixes even if the rule implements fix functions.

Add `meta.fixable` to fixable rules

---

src/rules/cognitive-complexity.ts
src/rules/max-switch-cases.ts
src/rules/no-all-duplicated-branches.ts
src/rules/no-collapsible-if.ts
src/rules/no-collection-size-mischeck.ts
src/rules/no-duplicate-string.ts
src/rules/no-duplicated-branches.ts
src/rules/no-element-overwrite.ts
src/rules/no-extra-arguments.ts
src/rules/no-identical-conditions.ts
src/rules/no-identical-expressions.ts
src/rules/no-identical-functions.ts
src/rules/no-inverted-boolean-check.ts
src/rules/no-one-iteration-loop.ts
src/rules/no-redundant-boolean.ts
src/rules/no-redundant-jump.ts
src/rules/no-same-line-conditional.ts
src/rules/no-small-switch.ts
src/rules/no-unused-collection.ts
src/rules/no-use-of-empty-return-value.ts
src/rules/no-useless-catch.ts
src/rules/prefer-immediate-return.ts
src/rules/prefer-object-literal.ts
src/rules/prefer-single-boolean-return.ts
src/rules/prefer-while.ts

Besides adding clarity to the rule intent, with fixable rules one can use `eslint --fix-type` to fix rules of one type only: https://eslint.org/docs/user-guide/command-line-interface#fix-type
**Update**: now builds on #161.

feat: add `meta.type`

---

src/rules/no-duplicate-string.ts
tests/rules/no-duplicate-string.test.ts

Fixes [#2464](https://github.com/SonarSource/SonarJS/issues/2464)

Improve S1192 by ignoring literals in type annotations

---

src/rules/no-unused-collection.ts
tests/rules/no-unused-collection.test.ts

Fix no-unused-collection: should not fire if collection is exported

---

src/rules/no-extra-arguments.ts
src/utils/locations.ts
tests/rules/no-extra-arguments.test.ts

Fixes #178 
The ticket mentions customising the message of the primary location with the function name depending on the callee type, which this user contribution does not include. I think we don't need to go that far as the location-based highlighting of an issue would be enough.

Rule S930: improve highlighting for no-extra-arguments

---

src/index.ts

We can't rely on the file system along with the file extension to retrieve the rule names. It won't work once packaged in the node modules. The reason is that `.ts` files are transformed into `.js` and `.d.ts` files.

Fix retrieval of rule names

---

src/utils/docs-url.ts
tests/index.test.ts

ruleFileName ends with .js after compilation
Unfortunately we didn't find a way to unit test the fixed problem

Fix link to docs in rule meta

---

src/rules/no-gratuitous-expressions.ts

Fix no-gratuitous-expressions: TypeError when accessing non-existing parent scope

---

src/rules/prefer-immediate-return.ts
tests/rules/prefer-immediate-return.test.ts

Improve 'prefer-immediate-return': ignore when returned variable has a declared type

---

.github/workflows/release.yml

This workflow does not follow the build once principle and should be enhanced, but last time we tried we did not managed to publish an already built artifact to npmjs.
Let's try at the next release.

Update release workflow to enforce artifacts management

---

.npmignore

This is to avoid the files being packaged in the release

Add Jfrog and WhiteSource config files to npmignore

---

README.md
docs/rules/no-redundant-jump.md
src/rules/no-redundant-jump.ts
tests/rules/no-redundant-jump.test.ts

https://github.com/SonarSource/SonarJS/issues/3016

Add suggestion for 'no-redundant-jump'

---

README.md
docs/rules/no-collection-size-mischeck.md
src/rules/no-collection-size-mischeck.ts
tests/rules/no-collection-size-mischeck.test.ts

https://github.com/SonarSource/SonarJS/issues/3021

Add suggestion for 'no-collection-size-mischeck'

---

README.md
docs/rules/prefer-single-boolean-return.md
src/rules/prefer-single-boolean-return.ts
tests/rules/prefer-single-boolean-return.test.ts

https://github.com/SonarSource/SonarJS/issues/3003

Add suggestion for 'prefer-single-boolean-return'

---

ruling/index.ts

Windows uses backlash instead of forward slash, so ruling reports changes on all files.
With this test, the ruling works as expected in Windows

fix windows ruling

---

.github/workflows/release.yml

- The "JF_ARTIFACTORY_" prefix is deprecated and to be removed in v3. Use the "JF_ENV_" prefix instead. 
- Update the secrets for using the team-dedicated ones.

BUILD-1751 fix JFrog credentials

---

package-lock.json
package.json

Fixes https://github.com/SonarSource/SonarJS/issues/4071
```bash
npm ls semver
eslint-plugin-sonarjs@0.21.0 /Users/ilia.kebets/Dev/Sonar/eslint-plugin-sonarjs
├─┬ @babel/core@7.22.9
│ ├─┬ @babel/helper-compilation-targets@7.22.10
│ │ └── semver@6.3.1 deduped
│ └── semver@6.3.1
├─┬ @babel/eslint-parser@7.18.9
│ └── semver@6.3.1 deduped
├─┬ @babel/preset-env@7.18.9
│ ├─┬ @babel/plugin-proposal-class-properties@7.18.6
│ │ └─┬ @babel/helper-create-class-features-plugin@7.22.10
│ │   └── semver@6.3.1 deduped
│ ├─┬ @babel/plugin-proposal-unicode-property-regex@7.18.6
│ │ └─┬ @babel/helper-create-regexp-features-plugin@7.22.9
│ │   └── semver@6.3.1 deduped
│ ├─┬ babel-plugin-polyfill-corejs2@0.3.3
│ │ ├─┬ @babel/helper-define-polyfill-provider@0.3.3
│ │ │ └── semver@6.3.1 deduped
│ │ └── …
```

Update dependencies for vulnerabilities

---

src/rules/no-identical-expressions.ts
tests/rules/no-identical-expressions.test.ts
tsconfig.json

Fix S17647(`no-identical-expressions`): Consider bigint for 1bit shifting as valid

---

ruling/snapshots/prefer-object-literal
src/rules/prefer-object-literal.ts
tests/rules/prefer-object-literal.test.ts

Fix FP S2428 (`prefer-object-literal`): Ignore circular reference assignments

---

README.md

Relates to https://github.com/SonarSource/eslint-plugin-sonarjs/issues/433

Update README: Plugin now requires Node.js 14 or higher

---

scripts/test-ci.sh
src/rules/no-use-of-empty-return-value.ts
tests/rules/no-use-of-empty-return-value.test.ts

Fixes https://github.com/SonarSource/SonarJS/issues/4579
This adds support for TSDeclareFunction function declaration. We consider 2 return types to be with no value: Void and Never.
Also, as part of this merge request, I update the rule to use TSESTree.AST_NODE_TYPES enum instead of strings.

Fix FP 3699 (no-use-of-empty-return-values) to handle ambient functions

---

src/rules/no-unused-collection.ts
tests/rules/no-unused-collection.test.ts

Fixes #449
As in the described issue, when accessing a collection items and performing a write on them, we can consider the collection as being used.
With removing the recursive call, we will now allow for code like:
let a = Array();
a[1][2] = 3; // mutates the underlying object, but a is being read.

Make no-unused-collection not trigger if writing to elements of said collection

---

package.json

The release process uses the project manifest as the package manifest, so we need to change the version there to allow the package to be published.

Bump the project manifest version to 0.25.1

---

src/rules/no-one-iteration-loop.ts

As described in https://github.com/eslint/eslint/issues/17457, CodePath#currentSegments is now removed. Fixing this following, the suggested implementation of the extraction of the currentSegment.

Fix breaking no-one-iteration-loop after ESLint v9 breaking change

---

package.json
sonar-project.properties

As we've updated the plugin to work with the latest eslint v9 version, and dropping support for eslint 5, 6 and 7. Let us bring it to a new major version.

Bump to version 1.0.0

---

.github/workflows/release.yml

With the updates to the packages we use, running a release fails - https://github.com/SonarSource/eslint-plugin-sonarjs/actions/runs/8936694762 . 
Husky v9.0.11 requires Node >= 18, let us increase it to try.
Adding @julien-carsique-sonarsource - as you already looked at our pipelines before on https://sonarsource.atlassian.net/browse/BUILD-4742 . I'm not sure how to test this change other than testing in production. In the ticket, you mention all of the steps that we are using in jfrog are also deprecated, so maybe it would be a good time to update them?

Increase node version on release from Node 12 -> 18

---

README.md
package-lock.json
package.json
ruling/index.ts
src/index.ts
tests/index.test.ts
tsconfig.json

Reading through the ESLint 9 compatibility issue tracker (https://github.com/eslint/eslint/issues/18093), one of the relevant items is the "meta" object to be exporting the name and version.
Once this lands and we release, I'll post to that thread that we are ready and compatible.

Export "meta" for plugin
