package.json
yarn.lock

@vilchik-elena don't forget to run `yarn` before checking

Add precommit hook

---

README.md
docs/rules/no-all-duplicated-branches.md
ruling/snapshots/no-all-duplicated-branches
src/index.ts
src/rules/no-all-duplicated-branches.ts
src/rules/no-duplicated-branches.ts
src/utils/conditions.ts
src/utils/equivalence.ts
tests/rules/no-all-duplicated-branches.test.ts

add no-all-duplicated-branches rule

---

README.md
docs/rules/no-extra-arguments.md
ruling/snapshots/no-extra-arguments
src/index.ts
src/rules/no-extra-arguments.ts
src/utils/nodes.ts
tests/rules/no-extra-arguments.test.ts

add no-extra-arguments rule

---

README.md
docs/rules/no-one-iteration-loop.md
ruling/snapshots/no-one-iteration-loop
src/index.ts
src/rules/no-one-iteration-loop.ts
src/utils/nodes.ts
tests/rules/no-one-iteration-loop.test.ts

add rule no-one-iteration-loop

---

src/rules/prefer-immediate-return.ts
tests/rules/prefer-immediate-return.test.ts

add code fix to prefer-immediate-return

---

src/rules/prefer-immediate-return.ts
tests/rules/prefer-immediate-return.test.ts

add semicolon to code fix of prefer-immediate-return

---

docs/rules/no-use-of-empty-return-value.md

Minor doc typo fox

---

src/utils/conditions.ts

fix a typo in comments

---

package.json

package.json: add eslint 5.x support

---

package.json

Include declarations in npm package

---

README.md
docs/rules/no-inverted-boolean-check.md
ruling/snapshots/no-inverted-boolean-check
src/index.ts
src/rules/no-inverted-boolean-check.ts
src/utils/nodes.ts
tests/rules/no-inverted-boolean-check.test.ts

add rule no-inverted-boolean-check

---

package.json
yarn.lock

upgrade lint-staged version to support node v10

---

README.md
docs/rules/no-useless-catch.md
ruling/snapshots/no-useless-catch
src/index.ts
src/rules/no-useless-catch.ts
tests/rules/no-useless-catch.test.ts

add no-useless-catch rule

---

README.md
docs/rules/max-switch-cases.md
ruling/snapshots/max-switch-cases
src/index.ts
src/rules/max-switch-cases.ts
tests/rules/max-switch-cases.test.ts

add max-switch-cases rule

---

ruling/snapshots/prefer-immediate-return
src/rules/prefer-immediate-return.ts
tests/rules/prefer-immediate-return.test.ts

FN prefer-immediate-return: consider hoisted variables

---

src/rules/no-extra-arguments.ts
src/utils/locations.ts
tests/rules/no-extra-arguments.test.ts

no-extra-arguments: provide secondary issue locations

---

src/rules/no-identical-functions.ts
tests/rules/no-identical-functions.test.ts

no-identical-functions: provide secondary issue locations

---

src/rules/no-element-overwrite.ts
tests/rules/no-element-overwrite.test.ts

no-element-overwrite: provide secondary issue locations

---

src/rules/no-identical-expressions.ts
tests/rules/no-identical-expressions.test.ts

no-identical-expressions: provide secondary issue locations

---

src/rules/no-identical-conditions.ts
tests/rules/no-identical-conditions.test.ts

no-identical-conditions: provide secondary issue locations

---

src/rules/cognitive-complexity.ts
src/utils/locations.ts
tests/rules/cognitive-complexity.test.ts

cognitive-complexity: provide secondary issue locations

---

docs/RELEASING.md
package.json

Add documentation about releasing and `prepack` npm hook to build the project

---

ruling/snapshots/no-duplicate-string
src/rules/no-duplicate-string.ts
tests/rules/no-duplicate-string.test.ts

FP no-duplicate-string: ignore strings used as object keys

---

src/rules/no-duplicated-branches.ts
tests/rules/no-duplicated-branches.test.ts

no-duplicated-branches: provide secondary issue locations

---

src/rules/no-duplicated-branches.ts
tests/rules/no-duplicated-branches.test.ts

no-duplicate-branches: Fix switch/case reporting

---

src/index.ts

feat: include plugin by default, close #117

---

.eslintrc.js
README.md
docs/rules/no-unused-collection.md
package.json
ruling/snapshots/no-unused-collection
src/index.ts
src/rules/no-unused-collection.ts
src/utils/collections.ts
tests/rules/no-unused-collection.test.ts
yarn.lock

add rule no-unused-collection

---

.eslintignore
README.md
docs/rules/no-collection-size-mischeck.md
src/index.ts
src/rules/no-collection-size-mischeck.ts
src/utils/parser-services.ts
tests/index.test.ts
tests/resources/tsconfig.json
tests/rules/no-collection-size-mischeck.test.ts
tsconfig.json

add rule no-collection-size-mischeck

---

docs/rules/no-duplicate-string.md
ruling/snapshots/no-duplicate-string
src/rules/no-duplicate-string.ts
tests/rules/no-duplicate-string.test.ts

FP no-duplicate-string: ignore JS directives

---

.editorconfig
.npmignore

- Add `.editorconfig` for before-the-fact IDE placement of indents

Editorconfig

---

.cirrus.yml
scripts/analyze_and_publish.sh

Update deploy to repox

---

README.md
docs/rules/no-empty-collection.md
ruling/snapshots/no-empty-collection
src/index.ts
src/rules/no-empty-collection.ts
src/utils/index.ts
src/utils/utils-ast.ts
src/utils/utils-collection.ts
src/utils/utils-parent.ts
tests/rules/no-empty-collection.test.ts

Rule S4158: Empty collections should not be accessed or iterated

---

README.md
docs/rules/no-nested-switch.md
ruling/snapshots/no-nested-switch
src/index.ts
src/rules/no-nested-switch.ts
tests/rules/no-nested-switch.test.ts

Rule S1821: "switch" statements should not be nested

---

ruling/snapshots/prefer-while
src/rules/prefer-while.ts
tests/rules/prefer-while.test.ts

Improve prefer-while: ignore 'for' without condition

---

README.md

Mention configuration in README

---

src/rules/prefer-immediate-return.ts
tests/rules/prefer-immediate-return.test.ts

Improve prefer-immediate-return: keep comments when fixing

---

README.md
docs/rules/no-ignored-return.md
src/rules/no-ignored-return.ts
src/utils/utils-type.ts
tests/rules/no-ignored-return.test.ts

Rule: Return values from functions without side effects should not be ignored

---

.github/workflows/release.yml

Publish in NPM version without build number

---

README.md
docs/rules/no-collection-size-mischeck.md
docs/rules/no-ignored-return.md
src/rules/no-collection-size-mischeck.ts
src/utils/parser-services.ts
tests/utils/parser-services.test.ts

Update and document the support of type-aware rules

---

package-lock.json
package.json

Use latest eslint sonarjs plugin for linting

---

docs/rules/cognitive-complexity.md

Fixes missing "sonarjs/" prefix for rule demo

---

src/rules/no-duplicate-string.ts
tests/rules/no-duplicate-string.test.ts

Improve S1192 ('no-duplicate-string'): add secondary location for each duplicate

---

src/rules/no-duplicate-string.ts
tests/rules/no-duplicate-string.test.ts

Fix no-duplicate-string: ignore import expressions

---

.github/workflows/release.yml

Config jfrog npm client before first use

---

README.md
package-lock.json
src/rules/no-inverted-boolean-check.ts
tests/rules/no-inverted-boolean-check.test.ts

Deactivate 'no-inverted-boolean' and replace fix with suggestion

---

package.json

Fix peerDependencies version format

---

.cirrus.yml
.cirrus/nodejs-12.Dockerfile
.cirrus/nodejs-14.Dockerfile
.cirrus/nodejs-15.Dockerfile

BUILD-1577 migrate to new infra and BUILD-1551 update repox credentials

---

src/rules/no-gratuitous-expressions.ts
tests/rules/no-gratuitous-expressions.test.ts

Fixes SonarSource/SonarJS#2807

fix rule to avoid FP on React conditional print

---

docs/rules/no-one-iteration-loop.md

Use "let" not "int" to declare the iteration variable
Fixes #

Update no-one-iteration-loop.md ("let", not "int")

---

.github/workflows/release.yml

BUILD-2298 Use default vault adress

---

.github/workflows/release.yml

BUILD-2298 Add missing permissions to the release wf

---

.cirrus.star
.cirrus.yml
.cirrus/nodejs-14.Dockerfile
.cirrus/nodejs-16.Dockerfile
.cirrus/nodejs-18.Dockerfile

BUILD-2330: Migrate to CirrusCI on AWS

---

.github/workflows/release.yml

BUILD-2298 Fix promotion

---

ruling/snapshots/no-identical-conditions
src/rules/no-identical-conditions.ts
tests/rules/no-identical-conditions.test.ts

Fixes https://github.com/SonarSource/SonarJS/issues/3696

Modify S1862 (`no-identical-conditions`): Detect duplicated condition overlaps

---

LICENSE
package-lock.json
package.json

Update license to `LGPL-3.0-only`

---

docs/rules/cognitive-complexity.md

Fixes https://github.com/SonarSource/eslint-plugin-sonarjs/issues/442

Fix cognitive complexity link

---

src/index.ts
tests/index.test.ts

Resolve ESLINTJS-37
